### PR TITLE
Handle zero outputs correctly

### LINKED ISSUE #265: Memleaks while displaying notifications with no display turned on
Hello,

this is [my own build](https://copr.fedorainfracloud.org/coprs/mhonek/sway/build/1327409/) from eaab1e1 which I made since I had troubles as described in #189 and/or #184 (and the respective commits actually fixed that issue for me). However, this introduced a different issue for me - a huge memleak (usually half of my RAM and half of my swap).

This seems to occur when there is a new notification while all the displays are turned off (external display is powered off and laptop's lid is closed). I do use swayidle and swaylock as well.

Components:
```
sway-1.4-1.fc31.x86_64
wlroots-0.10.1-1.fc31.x86_64
libwayland-client-1.17.0-2.fc31.x86_64
mako-1.4.1-1.20200404giteaab1e1.fc31.x86_64
```

The [runtime snapshot of the leaks acquired over a night](https://gist.github.com/kenoh/6809a0d9471901c164dd3c8377940f62) (the listing is a bit dirty but valid) is huge (there is a lot of pango mentioned but I presume this is due to some more substantial flaw) but the most important seem to be the biggest ones as listed below. The rest of the big loss records seems to be largely similar to these.
```
==4017455== 667,697,664 (166,925,472 direct, 500,772,192 indirect) bytes in 1,738,807 blocks are definitely lost in loss record 1,348 of 1,350
==4017455==    at 0x483980B: malloc (vg_replace_malloc.c:309)
==4017455==    by 0x4A753A8: g_malloc (gmem.c:99)
==4017455==    by 0x4A8D9D5: g_slice_alloc (gslice.c:1024)
==4017455==    by 0x4A8DFFD: g_slice_alloc0 (gslice.c:1050)
==4017455==    by 0x49F9111: g_type_create_instance (gtype.c:1849)
==4017455==    by 0x49DB3F4: g_object_new_internal (gobject.c:1827)
==4017455==    by 0x49DCB04: g_object_new_with_properties (gobject.c:1995)
==4017455==    by 0x49DD6B0: g_object_new (gobject.c:1667)
==4017455==    by 0x4C1A807: pango_font_map_create_context (pango-fontmap.c:72)
==4017455==    by 0x4C4FE6F: pango_cairo_create_context (pangocairo-context.c:434)
==4017455==    by 0x114251: create_buffer (pool-buffer.c:102)
==4017455==    by 0x114251: get_next_buffer (pool-buffer.c:143)
==4017455==    by 0x11554D: send_frame (wayland.c:462)
==4017455== 
==4017455== 2,382,943,680 bytes in 1,654,822 blocks are indirectly lost in loss record 1,349 of 1,350
==4017455==    at 0x483980B: malloc (vg_replace_malloc.c:309)
==4017455==    by 0x489DFFF: _cairo_default_context_create (cairo-default-context.c:1484)
==4017455==    by 0x114244: create_buffer (pool-buffer.c:101)
==4017455==    by 0x114244: get_next_buffer (pool-buffer.c:143)
==4017455==    by 0x11554D: send_frame (wayland.c:462)
==4017455==    by 0x553EAA7: ffi_call_unix64 (unix64.S:76)
==4017455==    by 0x553E2A3: ffi_call (ffi64.c:525)
==4017455==    by 0x4C6E5E7: ??? (in /usr/lib64/libwayland-client.so.0.3.0)
==4017455==    by 0x4C6AF17: ??? (in /usr/lib64/libwayland-client.so.0.3.0)
==4017455==    by 0x4C6C46B: wl_display_dispatch_queue_pending (in /usr/lib64/libwayland-client.so.0.3.0)
==4017455==    by 0x111A98: run_event_loop (event-loop.c:267)
==4017455==    by 0x10F546: main (main.c:113)
==4017455== 
==4017455== 3,720,030,832 (648,690,224 direct, 3,071,340,608 indirect) bytes in 1,654,822 blocks are definitely lost in loss record 1,350 of 1,350
==4017455==    at 0x483980B: malloc (vg_replace_malloc.c:309)
==4017455==    by 0x48AD5B8: _cairo_image_surface_create_for_pixman_image (cairo-image-surface.c:185)
==4017455==    by 0x48ADA00: _cairo_image_surface_create_with_pixman_format (cairo-image-surface.c:355)
==4017455==    by 0x114237: create_buffer (pool-buffer.c:99)
==4017455==    by 0x114237: get_next_buffer (pool-buffer.c:143)
==4017455==    by 0x11554D: send_frame (wayland.c:462)
==4017455==    by 0x553EAA7: ffi_call_unix64 (unix64.S:76)
==4017455==    by 0x553E2A3: ffi_call (ffi64.c:525)
==4017455==    by 0x4C6E5E7: ??? (in /usr/lib64/libwayland-client.so.0.3.0)
==4017455==    by 0x4C6AF17: ??? (in /usr/lib64/libwayland-client.so.0.3.0)
==4017455==    by 0x4C6C46B: wl_display_dispatch_queue_pending (in /usr/lib64/libwayland-client.so.0.3.0)
==4017455==    by 0x111A98: run_event_loop (event-loop.c:267)
==4017455==    by 0x10F546: main (main.c:113)
==4017455== 
==4017455== LEAK SUMMARY:
==4017455==    definitely lost: 936,280,232 bytes in 3,477,446 blocks
==4017455==    indirectly lost: 3,639,918,392 bytes in 17,391,812 blocks
==4017455==      possibly lost: 521,162 bytes in 1,194 blocks
==4017455==    still reachable: 1,330,602 bytes in 11,371 blocks
==4017455==                       of which reachable via heuristic:
==4017455==                         length64           : 144 bytes in 3 blocks
==4017455==                         newarray           : 1,600 bytes in 20 blocks
==4017455==         suppressed: 0 bytes in 0 blocks
==4017455== 
==4017455== 
==4017455== HEAP SUMMARY:
==4017455==     in use at exit: 4,578,053,820 bytes in 20,881,843 blocks
==4017455==   total heap usage: 408,835,696 allocs, 387,953,853 frees, 32,875,353,493 bytes allocated
```

When the leak is happening the CPU spins a lot (loud fan). A phenomenon observed is that while the CPU is spinning I open the laptop's lid, the CPU goes down, however after just closing it again it goes crazy again. My layman thinking leads to an idea that while the displays are off mako is trying to draw the notification but fails (keeping some memory allocated) but then tries again right after that and this way causing continuous memleak.

Thanks for all the help in advance.

### PR DESCRIPTION
**Pull request by Emantor**
Add handling to handle zero outputs and restore surfaces correctly from zero to one or more outputs.

Fixes #265

### CODE REVIEW

File: wayland.c [hunk 1]
```diff
@@ -75,11 +79,22 @@ static void create_output(struct mako_state *state,
 	output->global_name = global_name;
 	output->wl_output = wl_output;
 	output->scale = 1;
+
+	if (wl_list_empty(&state->outputs)) {
+		recreate_surface = true;
+	}
```
Comment (vilhalmer) [inline wayland.c:85]: This can be simplified to `bool recreate_surface = wl_list_empty(...)`.

File: wayland.c [hunk 2]
```diff
@@ -75,11 +79,22 @@ static void create_output(struct mako_state *state,
...
+
 	wl_list_insert(&state->outputs, &output->link);
 
 	wl_output_set_user_data(wl_output, output);
 	wl_output_add_listener(wl_output, &output_listener, output);
 	get_xdg_output(output);
+	if (recreate_surface) {
+		// We had no outputs, force our surfaces to redraw
+		wl_list_for_each(surface, &output->state->surfaces, link) {
+			send_frame(surface);
```
Comment (vilhalmer) [inline wayland.c:95]: I think this should use `set_dirty` instead of sending the frame directly, just to keep the code path consistent. It should have the same effect of immediately drawing a frame in this case since the underlying surfaces will have been gone.

(Are we cleaning them up properly when the last output goes away?)

**Review by vilhalmer — CHANGES_REQUESTED** [review]
Thanks for the PR! This approach looks generally correct to me, just a couple comments.

File: wayland.c (hunk 2 above)
Comment (Emantor) [reply wayland.c:93]: Done.

When the last output goes away, one of the buffers may still be marked as busy, however the compositor should release it soon after. When restarting with one or more outputs, the get_next_buffer() code should clean it up.

**Review by emersion — APPROVED** [review]
LGTM, thanks!

**Comment by norpol** [comment]
Thank you so much as well!
